---PARTITION BY: THIS IS OFTEN COMPARE TO THE 'GROUP BY' STATEMENT BUT THE 'GROUP BY' STATEMENT IS SLIGHTLY DIFFERENT. 
---THE GROUP BY STATEMEMNT IS GOING TO REDUCE THE NUMBER OF ROWS IN OUR TABLE BY ACTUALLY ROLLING IT UP AND THEN
---CALCULATING THE SUM OR AVERAGE FOR EACH GROUP WHEREAS 'PARTITION BY' ACTUALLY DIVIDES THE RESULTS INTO PARTITIONS
---AND CHANGES HOW THE WINDOW FUNCTION IS CALCULATED. SO PARTITION BY DOESNT ACTUALLY REDUCE THE NUMBER OF ROWS IN THE OUTPUT.

SELECT *
FROM EmployeeDemographics

SELECT *
FROM EmployeeSalary

----WE WILL JOIN THESE TWO TABLES USING THE GENDER COLUMN AND THE SALARY COLUMN.

SELECT *
FROM EmployeeDemographics Edem
JOIN EmployeeSalary Esal
ON Edem.EmployeeID=Esal.EmployeeID

---USING THE PARTITION BY STATEMENT, WE WILL JOIN THE TWO TABLES USING THE FIRSTNAME,LASTNAME,GENDER AND SALARY COLUMNS.
-- THEN WE WILL GET A COUNT OF THE TOTAL NUMBER OF EACH GENDER AND INCLUDE THIS ON EACH LINE

SELECT FirstName, LastName, Gender, Salary
 , COUNT(Gender) OVER (PARTITION BY Gender) As TotalGender
FROM EmployeeDemographics Edem
JOIN EmployeeSalary Esal
ON Edem.EmployeeID=Esal.EmployeeID

-- IF WE TRY TO DO SAME THING AS ABOVE WITH THE GROUP BY STATEMENT, WE WOULD NOT BE ABLE TO GET THE TOTAL NUMBER OF EACH GENDER FOR EACH LINE AS WE 
---DID WITH THE PARTITION BY STATEMENT

SELECT FirstName, LastName, Gender, Salary,COUNT(Gender) 
FROM EmployeeDemographics Edem
JOIN EmployeeSalary Esal
ON Edem.EmployeeID=Esal.EmployeeID
GROUP BY FirstName, LastName, Gender, Salary

---THE MOST WE CAN DO TO GET THE TOTAL NUMBER OF GENDER IS TO USE THE FOLLOWING STATEMENT 
---WHICH DOESN'T SHOW THE INDIVIDUAL LINES LIKE THE PARTITION BY STATEMENT

SELECT  Gender,COUNT(Gender) 
FROM EmployeeDemographics Edem
JOIN EmployeeSalary Esal
ON Edem.EmployeeID=Esal.EmployeeID
GROUP BY Gender