---GROUP BY,ORDER BY

---USING THE GROUP BY STATEMENT. WITH THE GROUP BY STATEMENT, WE CAN ADD THE COUNT COMMAND SO THAT IT SHOWS THE TOTAL NUMBER OF COUNTS OF EACH GENDER
SELECT GENDER
FROM EmployeeDemographics
GROUP BY Gender

SELECT GENDER,COUNT(GENDER)
FROM EmployeeDemographics
GROUP BY Gender

SELECT GENDER,AGE,COUNT(GENDER)
FROM EmployeeDemographics
GROUP BY Gender,Age

SELECT GENDER,AGE,COUNT(GENDER)
FROM EmployeeDemographics
WHERE AGE>34
GROUP BY Gender,Age

SELECT GENDER,COUNT(GENDER) AS CountGender
FROM EmployeeDemographics
WHERE AGE>34
GROUP BY Gender ORDER BY Gender ASC

---ASC WILL ARRANGE THE OUTPUT IN ALPHABETICAL ORDER WHILE DESC WILL ORDER IN DESCENDING ORDER

---THE FIRST SCRIPT ABOVE IS THE SAME AS USING THE DISTINCT COMMAND BELOW.BUT WE CANNOT ADD THE COUNT TO THE DISTINCT STATEMENT
SELECT DISTINCT(GENDER)
FROM EmployeeDemographics



---USING THE ORDER BY STATEMENT
SELECT EmployeeID,FirstName,LastName
FROM EmployeeDemographics
ORDER BY EmployeeID


SELECT *
FROM EmployeeDemographics
ORDER BY Gender 

SELECT *
FROM EmployeeDemographics
ORDER BY Gender DESC

SELECT *
FROM EmployeeDemographics
ORDER BY Gender,Age 

SELECT *
FROM EmployeeDemographics
ORDER BY AGE,Gender 

SELECT *
FROM EmployeeDemographics
ORDER BY AGE DESC,Gender DESC

---WE CAN ALSO USE NUMBERS TO REPRESENT THE COLUMNS WHEN WRITING THE ORDER BY STATEMENT. EMPLOYEEID=1,FIRSTNAME=2,LASTNAME=3,AGE=4 AND GENDER=5 IN ORDER LIKE THAT
SELECT EmployeeID,FirstName,LastName
FROM EmployeeDemographics
ORDER BY 1


SELECT *
FROM EmployeeDemographics
ORDER BY 5 

SELECT *
FROM EmployeeDemographics
ORDER BY 5 DESC

SELECT *
FROM EmployeeDemographics
ORDER BY 5,4 

SELECT *
FROM EmployeeDemographics
ORDER BY 4,5 

SELECT *
FROM EmployeeDemographics
ORDER BY AGE DESC,Gender DESC
