---SELECT STATEMENT: *,TOP,DISCTINCT,COUNT,AS,MAX,MIN,AVG 
---USING SELECT WITH 'TOP' TO SELECT THE FIRST 1000 CONTENT IN EMPLOYEEDEM AND EMPLOYEESAL TABLES:

SELECT TOP (1000) [EmployeeID]
      ,[FirstName]
      ,[LastName]
      ,[Age]
      ,[Gender]
  FROM [SQL Tutorial].[dbo].[EmployeeDemographics]
  
---EmployeeSalary TABLE
SELECT TOP (1000) [EmployeeID]
      ,[JobTitle]
      ,[Salary]
  FROM [SQL Tutorial].[dbo].[EmployeeSalary]
 

  ---INSTEAD OF USING THE SELECT TOP 1000 STATEMENT, WE WILL USE THE SIMPLE STATEMENT BELOW:

  SELECT*
  FROM EmployeeDemographics

  ---EMPLOYEESAL TABLE

  SELECT*
  FROM EmployeeSalary
  
  ---ABOVE QUERIE SELECTS ALL(*) INFORMATION IN OUR EMPLOYEEDEMO AND EMPLOYEESAL TABLES
  ---
  ---USING SELECT STATEMENT WITH DISTINCT:

SELECT DISTINCT EmployeeID,GENDER
  FROM dbo.EmployeeDemographics

  SELECT DISTINCT EMPLOYEEID,JOBTITLE,SALARY
  FROM EmployeeSalary
  ---
 --- USING SELECT STATEMENT WITH COUNT:

  SELECT COUNT(EMPLOYEEID)
  FROM EmployeeDemographics

  SELECT COUNT(EMPLOYEEID)
  FROM EmployeeDemographics
  WHERE GENDER='MALE'

  SELECT COUNT(EMPLOYEEID)
  FROM EmployeeDemographics
  WHERE AGE>=30

  ---SELECT STATEMENT WITH AS AND AVG. THE AS COMMAND TELLS OUR QUERIE TO RENAME THE RESULT COLUMN JUST AS 
  ---SHOWN BELOW. OUR RESULT COLUMN FOR EMPLOYEEID COUNT IS NAME IDcnt. 

  SELECT COUNT(EMPLOYEEID) AS IDcnt
  FROM EmployeeDemographics
  WHERE AGE>=30
  ---THE AVG STATEMENT FINDS THE AVERAGE OF SALARIES OVER OR EQUAL TO 30000 AND RENAMES THE COLUMN AVGSal.
  SELECT AVG(SALARY) AS AVGSal
  FROM EmployeeSalary
  WHERE SALARY>=30000

  ---SELECT STATEMENT WITH MIN & MAX:MIN SHOWS THE MINIMUM VALUE OF A QUERIE AND NAMES THE COLUMN MinSal WITHOUT USING THE 
  ---AS STATEMENT..THE RESULT IS THE SAME AS WHEN WE USE THE AS STATEMENT.

  SELECT MIN(salary) MinSal
  FROM EmployeeSalary
  ---WHILE MAX FINDS THE MAX VALUE OF A QUERIED COLUMN AND RENAMES THE RESULT COLUMN AS MaxSal
  SELECT MAX(salary) MaxSal
  FROM EmployeeSalary

  