---UNION AND UNION OR

---THE DIFFERENCE BETWEEN JOIN AND UNION IS THAT JOIN IS USED TO COMBINE TWO TABLES BASED ON A COMMON COLUMN IE EMPLOYEEID. 
---WITH UNION YOU'RE ABLE TO SELECT BOTH TABLES AND PUT THE DATA IN ONE OUTPUT I.E THE TABLES HAVE SIMILAR COLUMNS 
---SO YOU CAN PUT ALL THE DATA OF SIMILAR COLUMNS IN 1 SINGLE COLUMN. SO TO JOIN TWO TABLES USING 'UNION', THEY MUST HAVE EQUAL NUMBER OF COLUMNS

SELECT*
FROM EmployeeDemographics

SELECT* 
FROM WareHouseEmployeeDemographics

---THESE 2 TABLES ARE EXACTLY THE SAME NUMBER OF COLUMNS AND WITH THE EXACT SAME COLUMN NAMES.
---SO WE CAN USE THE UNION CAMMAND TO COMBINE THE TWO TABLES INTO ONE OUTPUT AS SHOWN BELOW.
---THE UNION COMMAND REMOVES DUPLICATES
SELECT*
FROM EmployeeDemographics
UNION
SELECT* 
FROM WareHouseEmployeeDemographics
ORDER BY EmployeeID

---THE UNION ALL INCLUDES ALL DUPLICATES

SELECT*
FROM EmployeeDemographics
UNION ALL
SELECT* 
FROM WareHouseEmployeeDemographics
ORDER BY EmployeeID

---WE CAN ALSO USE UNION TO COMBINE TABLES WITH DIFFERENT COLUMNS

SELECT*
FROM EmployeeDemographics

SELECT*
FROM EmployeeSalary

---THESE ARE TWO TABLES WITH DIFFERENT COLUMNS WE CAN COMBINE THE TWO TABLES BY CHOOSING TO MADGE SIMILAR COLUMNS IE

SELECT EmployeeID,FirstName,Age
FROM EmployeeDemographics
UNION
SELECT EmployeeID,JobTitle,Salary
FROM EmployeeSalary

---WE ARE ABLE TO COMBINE THE TWO TABLES THIS WAY BECAUSE EMPLOYEE IDs ARE VARCHAR, 
---FIRSTNAME AND JOBTITLE ALSO VARCHAR AND AGE/SALARY ARE INTEGERS

