
---INNER JOIN,FULL/LEFT/RIGHT/OUTER JOINS

---INNER JOIN IS A WAY OF COMBINING MULTIPLE TABLES INTO A SINGLE OUTPUT USING A COMMON COLUMN

---THESE TWO TABLES HAS THE EMPLOYEEID COLUMN IN COMMON AND THIS IS WHAT WE WILL USE TO PERFORM THE JOIN.
SELECT *
FROM EmployeeSalary

SELECT *
FROM EmployeeDemographics

---THE INNER JOIN COMMAND COMBINES SIMILAR/COMMON/OVERLAP THINGS FROM THE TWO TABLES.
SELECT *
FROM EmployeeDemographics
INNER JOIN EmployeeSalary
ON EmployeeDemographics.EmployeeID=EmployeeSalary.EmployeeID

---THE FULL OUTER JOIN COMMAND COMBINES EVERYTHING FROM THE TWO TABLES.

SELECT *
FROM EmployeeDemographics
FULL OUTER JOIN EmployeeSalary
ON EmployeeDemographics.EmployeeID=EmployeeSalary.EmployeeID

---THE LEFT OUTER JOIN COMMAND TAKES EVERYTHING FROM THE LEFT TABLE REGARDLESS OF WHETHER THERE'S A MATCH IN THE RIGHT TABLE.

SELECT *
FROM EmployeeDemographics
LEFT OUTER JOIN EmployeeSalary
ON EmployeeDemographics.EmployeeID=EmployeeSalary.EmployeeID

---THE RIGHT OUTER JOIN COMMAND TAKES EVERYTHING FROM THE RIGHT TABLE REGARDLESS OF WHETHER THERE'S A MATCH IN THE LEFT TABLE.

SELECT *
FROM EmployeeDemographics
RIGHT OUTER JOIN EmployeeSalary
ON EmployeeDemographics.EmployeeID=EmployeeSalary.EmployeeID

---WE CAN DO JOIN USING THE PARTICULAR COLUMNS WE WANT TO RETURN.

---USE CASE1: MICHAEL WANTS TO DO A PAY CUT FOR THE HIGHEST PAID EMPLOYEE APART FROM HIMSELF. 
---THE FOLLOWING SCRIPT IS USED TO FIGURE OUT THE HIGHEST PAID (SIMI FESO) USING THE EMPLOYEE DEM AND SAL TABLES

SELECT EmployeeDemographics.EmployeeID,FirstName,LastName,Salary
FROM EmployeeDemographics
INNER JOIN EmployeeSalary
ON EmployeeDemographics.EmployeeID=EmployeeSalary.EmployeeID
WHERE FirstName<>'Michael'
ORDER BY Salary DESC

---USECASE2: THE ACCOUNTANT (KEVIN MALONE) FEELS HE HAS MADE A MISTAKE IN CALCULATING THE AVERAGE SALARY PER SALESMEN.

SELECT JobTitle,AVG(Salary)
FROM EmployeeDemographics
INNER JOIN EmployeeSalary
ON EmployeeDemographics.EmployeeID=EmployeeSalary.EmployeeID
WHERE JOBTITLE='SALESMAN'
GROUP BY JobTitle

